export const routes = [{
  path: '/home',
  component: require('./components/Home.vue').default
}, {
  path: '/account',
  component: require('./components/Account.vue').default
}, {
  path: '/inhabitant',
  component: require('./components/Inhabitant.vue').default
}, {
  path: '/calendar',
  component: require('./components/Calendar.vue').default
}, {
  path: '/household',
  component: require('./components/Household.vue').default
}, {
  path: '/barangayclearance',
  component: require('./components/BarangayClearance.vue').default
}, {
  path: '/printdocument',
  component: require('./components/PrintDocument.vue').default
}, {
  path: '/childrenWithConflict',
  component: require('./components/ChildrenWithConflicts.vue').default
}, {
  path: '/listOfRegisteredVoters',
  component: require('./components/ListOfRegisteredVoters.vue').default
}, {
  path: '/listOfProspectiveSkVoters',
  component: require('./components/ListOfProspectiveSKVoters.vue').default
}, {
  path: '/listOfSeniorCitizens',
  component: require('./components/ListOfSeniorCitizens.vue').default
}, {
  path: '/listOfOutOfSchoolYouth7-14',
  component: require('./components/ListOfOutOfSchoolYouth7-14.vue').default
}, {
  path: '/listOfOutOfSchoolYouth15-25',
  component: require('./components/ListOfOutOfSchoolYouth15-25.vue').default
}]
